main: me.playbosswar.com.Main
name: "${project.name}"
version: "${project.version}"
description: "${project.description}"
author: PlayBossWar
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  commandtimer:
    usage: /<command>
    aliases: [cmt]
    description: List all commands
  worldtime:
    usage: /<command>
    description: Show real time of current minecraft world